/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Cyber Emerald palette
        'primary':                  '#f0ffe9',
        'on-primary':               '#00390d',
        'primary-container':        '#2dff5f',
        'on-primary-container':     '#007222',
        'secondary':                '#b1ceb4',
        'on-secondary':             '#1d3624',
        'secondary-container':      '#334d39',
        'on-secondary-container':   '#9fbca4',
        'tertiary':                 '#eeffec',
        'on-tertiary':              '#013918',
        'tertiary-container':       '#b4ebbb',
        'on-tertiary-container':    '#3a6c45',
        'surface':                  '#0f1511',
        'surface-dim':              '#0f1511',
        'surface-bright':           '#343b36',
        'surface-container-lowest': '#09100c',
        'surface-container-low':    '#171d19',
        'surface-container':        '#1b211d',
        'surface-container-high':   '#252b27',
        'surface-container-highest':'#303632',
        'on-surface':               '#dee4de',
        'on-surface-variant':       '#bacbb5',
        'outline':                  '#849580',
        'outline-variant':          '#3b4b39',
        'surface-tint':             '#00e54e',
        'background':               '#0f1511',
        'on-background':            '#dee4de',
        'neon':                     '#2dff5f',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display':    ['64px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-xl':['48px', { lineHeight: '1.1',  fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg':['32px', { lineHeight: '1.2',  fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md':['24px', { lineHeight: '1.3',  fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':    ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'label-md':   ['14px', { lineHeight: '1.0',  fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm':   ['12px', { lineHeight: '1.0',  fontWeight: '500', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        xs:     '8px',
        sm:     '16px',
        md:     '24px',
        lg:     '48px',
        xl:     '80px',
        gutter: '24px',
        margin: '32px',
      },
      boxShadow: {
        'neon-sm': '0 0 8px rgba(45, 255, 95, 0.3)',
        'neon':    '0 0 20px rgba(45, 255, 95, 0.4)',
        'neon-lg': '0 0 40px rgba(45, 255, 95, 0.2)',
      },
    },
  },
  plugins: [],
}
