import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Dynamic (CSS variables from layout.json via BaseLayout) ──
        'neon':                     'rgb(var(--tw-accent) / <alpha-value>)',
        'on-surface':               'rgb(var(--tw-text) / <alpha-value>)',
        'on-background':            'rgb(var(--tw-text) / <alpha-value>)',
        'background':               'rgb(var(--tw-bg) / <alpha-value>)',
        'surface':                  'rgb(var(--tw-surface) / <alpha-value>)',
        'surface-dim':              'rgb(var(--tw-surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--tw-bg) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--tw-surface) / <alpha-value>)',
        'surface-container':        'rgb(var(--tw-surface-high) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--tw-surface-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--tw-surface-high) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--tw-text-muted) / <alpha-value>)',
        'outline':                  'rgb(var(--tw-text-muted) / <alpha-value>)',
        // ── Static ──
        'primary':                  '#eeeeff',
        'on-primary':               '#0010a0',
        'primary-container':        '#404dff',
        'on-primary-container':     '#d0d0ff',
        'secondary':                '#c4c3e0',
        'on-secondary':             '#2d2d4f',
        'secondary-container':      '#25265a',
        'on-secondary-container':   '#c4c3e0',
        'tertiary':                 '#e8e0ff',
        'on-tertiary':              '#1a0048',
        'tertiary-container':       '#6b4fcc',
        'on-tertiary-container':    '#e8e0ff',
        'surface-bright':           '#323356',
        'outline-variant':          '#40426a',
        'surface-tint':             '#6b74ff',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display':    ['64px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-xl':['48px', { lineHeight: '1.1',  fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg':['32px', { lineHeight: '1.2',  fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md':['24px', { lineHeight: '1.3',  fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':    ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'label-md':   ['14px', { lineHeight: '1.0',  fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm':   ['12px', { lineHeight: '1.0',  fontWeight: '500', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        xs:     '8px',
        sm:     '16px',
        md:     '24px',
        lg:     '48px',
        xl:     '80px',
        gutter: '24px',
        margin: '32px',
      },
      boxShadow: {
        'neon-sm': '0 0 8px rgb(var(--tw-accent) / 0.3)',
        'neon':    '0 0 20px rgb(var(--tw-accent) / 0.4)',
        'neon-lg': '0 0 40px rgb(var(--tw-accent) / 0.2)',
      },
    },
  },
  plugins: [typography],
}
